services:
  - type: web
    name: weather-frontend
    env: node
    plan: free  # 무료 플랜 사용
    region: singapore  # 아시아 지역 선택
    buildCommand: |
      npm install --production
      npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://weather-backend-knii.onrender.com
      - key: VITE_UPLOAD_URL
        value: https://weather-backend-knii.onrender.com/upload
    autoDeploy: true

  - type: web
    name: weather-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.mongodb.net/weather?retryWrites=true&w=majority
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://weather-of7u.onrender.com
      - key: LOG_LEVEL
        value: info
    autoDeploy: true 